version: "3.9"
services:
  database:
    image: postgres:16
    container_name: atak-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atak-network

  web:
    build: .
    container_name: atak-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/mydb?schema=public"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - atak-network

volumes:
  database_data:

networks:
  atak-network:
    driver: bridge
